config/routes.rb
Rails.application.routes.draw do

  root 'urls#index'

  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  resources :users,    only: [:new, :create, :edit]
  resources :comments, only: [:create, :destroy]
  resources :urls do
    resources :votes,  only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to  :url
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user
  has_many :comments
  has_many :votes
  has_many :voters, through: :votes, source: :user 
end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user
  has_many :comments
  has_many :votes
  has_many :voters, through: :votes, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email
  validates :email, format: {
              with: /.+@.+\..+/,  message: 'Invalid email address.'
            }
  has_many :urls
  has_many :comments
  has_many :votes
  has_many :voted_posts, through: :votes, source: :url
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates_presence_of :user_id, :url_id, :score
  validates :user_id, uniqueness: {
             scope: :url_id,
             message: 'one vote per link'
          }
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in_user

  def logged_in_user
    user_id = session['user_id']
    if user_id
      User.find_by(id: user_id)
    end
  end

  def authenticate!
    unless logged_in_user
      flash[:notice] = "must be logged in"
      redirect_to root_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @url = Url.find_by(params['id'])
    @url.comments.create(comment_params)
    redirect_to url_path(@url)
  end

  private

  def comment_params
    params.require(:comments).permit(:body, :user_id)
  end
end

app/controllers/redirects_controller.rb
class RedirectController < ApplicationController
  def index
    redirect_to :root, :status => :moved_permanently
  end
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    @user = User.find_by(email: params['email'])
    if @user && @user.authenticate(params['password'])
      session[:user_id] = @user.id
      flash[:notice] = 'Logged in.'
      redirect_to root_url
    else
      flash['notice'] = 'No matches found.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate!, except: [:index,:show]

  def index
    @urls = Url.all
    render 'index'
  end

  def new
    @url = Url.new
    if logged_in_user
      render 'new'
    else
      flash[:notice] = "login to add post"
      redirect_to root_url
    end
  end

  def show
    @url = Url.find(params['id'])
    render 'show'
  end

  # def create
  #   if !params[:url].blank?
  #     client = Bitly.client
  #     @url = client.shorten(params['url'])
  #     redirect_to root_url
  #   end
  # end

  def create
    url = logged_in_user.urls.new(url_params)
    client = Bitly.client
    address = client.shorten(params['address'])
    if url.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @url = Url.find(params['id'])
  end

  def update
    url = Url.find(params['id'])
    url.update(title: params['title'])
    redirect_to root_path
  end

  def destroy
    url = Url.find(params['id'])
    if logged_in_user.id == url.user_id
      url.destroy
    else
      flash[:notice] = 'access denied'
    end
    redirect_to root_url
  end

  private

  def url_params
    params.permit(:title, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session['user_id'] = @user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params['id'])
  end

  private

  def user_params
    params.permit(:name, :email, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate!

  def create
    @vote = logged_in_user.votes.new(url_id: params[:url_id],
                                     score: params[:score])
    flash[:notice] = 'unable to do that action' unless @vote.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reddit_helper.rb
module RedditHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-3'>
        <small>about</small>
          <li><a class='choice' href='https://www.reddit.com/blog/'>blog</a></li>
          <li><a class='choice' href='https://www.reddit.com/about/'>about</a></li>
          <li><a class='choice' href='https://www.reddit.com/about/values/'>values</a></li>
          <li><a class='choice' href='https://www.reddit.com/code/'>source code</a></li>
          <li><a class='choice' href='https://www.reddit.com/advertising/'>advertise</a></li>
          <li><a class='choice' href='https://www.reddit.com/jobs/'>jobs</a></li>
      </div>
      <div class='col-md-3'>
        <small>help</small>
          <li><a class='choice' href='https://www.reddit.com/rules/'>site rules</a></li>
          <li><a class='choice' href='https://reddit.zendesk.com'>FAQ</a></li>
          <li><a class='choice' href='https://reddit.com/wiki/'>wiki</a></li>
          <li><a class='choice' href='https://www.reddit.com/wiki/reddiquette/'>reddiquette</a></li>
          <li><a class='choice' href='https://www.reddit.com/wiki/transparency/'>transparency</a></li>
          <li><a class='choice' href='https://www.reddit.com/contact'>contact us</a></li>
      </div>
      <div class='col-md-3'>
        <small>apps & tools</small>
          <li><a class='choice'>Reddit for Iphone</a></li>
          <li><a class='choice'>Reddit for Android</a></li>
          <li><a class='choice' href='https://m.reddit.com'>mobile website</a></li>
          <li><a class='choice' href='https://www.reddit.com/buttons/'>buttons</a></li>
      </div>
      <div class='col-md-3'>
        <small><3</small>
          <li><a class='choice-gold' href='https://www.reddit.com/gold/about/'>reddit gold</a></li>
          <li><a class='choice' href='http://redditgifts.com'>redditgifts</a></li>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class='nav-bar'>

  <!-- <div class='nav-account'>
    <% if logged_in_user %>
    <ul class='nav-logged'>
      <li><%= link_to logged_in_user.name, edit_user_path(logged_in_user.id) %></li>
      <li><%= link_to 'preferences', '#'%></li>
      <li><%= link_to 'logout', logout_path, method: :delete%></li>
    </ul>
    <% else %>
    <ul class='nav-not-logged'>
      <li><%= link_to 'log in', login_path(@user) %></li>
      <li><%= link_to 'sign up', new_user_path %></li>
    </ul>
    <% end %>
    </div>
  </div> -->

  <div class='nav' role='navigation'>
      <div class='col-md-12'>
        <%= image_tag('reddit.png', alt: 'Reddit Icon') %>
        <li><a href='#' style='color:red;'>hot</a></li>
        <li><a href='#'>new</a></li>
        <li><a href='#'>rising</a></li>
        <li><a href='#'>controversial</a></li>
        <li><a href='#'>top</a></li>
        <li><a href='#'>gilded</a></li>
        <li><a href='#'>wiki</a></li>
        <li><a href='#'>promoted</a></li>
        <% if logged_in_user %>
        <li><%= link_to logged_in_user.name, edit_user_path(logged_in_user.id) %></li>
        <li><%= link_to 'preferences', '#'%></li>
        <li><%= link_to 'logout', logout_path, method: :delete%></li>
        <% else %>
        <li style='margin-left:42em;'><%= link_to 'log in', login_path(@user) %></li>
        <li><%= link_to 'sign up', new_user_path %></li>
        <% end %>
      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Convergeddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% if flash[:notice] %>
    <medium class='alert'><%= flash[:notice] %></medium>
  <% end %>

<%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/links/index.html.erb
<ol class="links">
  <% @links.each do |link| %>
    <div class="link-anchor">
      <li>
        <!-- TODO CORRECT LINK TITLE / COMMENT  -->
        <h4><%= link_to link.title, link_path(link) %></h4></br>
        <%= simple_format(link.url) %>
        (<%= link.votes.sum(:score) %> points)
        <%= link_to 'up', link_votes_path(link, score: 1), method: :post %>
        <%= link_to 'down', link_votes_path(link, score: -1), method: :post %>
        <p class="link-date">submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></p>
        <%= link_to("comments", link_path(link)) %>
        <%= link_to("edit", edit_link_path(link)) %>
        <%= link_to("delete", link_path(link), method: :delete) %>
        <span>share</span>
        <span>save</span>
        <span>hide</span>
        <span>report</span>
      </li>
  <% end %>
</ol>

<div class='side'>
  <div class='spacer'>
    <%= link_to 'Submit a new link', new_link_path %>
  </div>
  <div class='spacer'>
    <%= link_to 'Submit a new text post', '#' %>
  </div>
</div>

app/views/links/show.html.erb
<%= render partial: 'link', locals: {link: @link} %>


<h7 class='comments_count'>
  <span>top </span><%= @link.comments.count %> comments<span> show all blah</span>
</h7>

<div class='comments-form'>
    <h6>top 200 comments</h6><%= link_to '#' %>
    <%= form_tag links_path @link.id do %>
      <div class='comment-field'>
          <%= label_tag('Comment') %>
          <%= text_area_tag('body') %>
      </div>
      <%= button_tag('save') %>
    <% end %>
</div>

<div class='comments-list'>
  <% @link.comments.each do |comment| %>
      <div class='comment-post'>
          <%= User.find(comment.id).name %>
          <%= simple_format(comment.body) %>
      </div>
  <% end %>
</div>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
  <div class='url-field'> <br/>
    <%= label_tag('title') %> <br/>
    <%= text_field_tag @url.title %>
  </div>
  <div class='url-field'>
    <%= label_tag('address') %> <br/>
    <%= text_field_tag @url.address %>
  </div>
  <br>
  <%= button_tag 'submit' %>
<% end %>

app/views/urls/_url.html.erb
<h2 class='url-title'><%= link_to_unless_current(url.title, url_path) %></h2>
<p class='url-date'>submitted <%= time_ago_in_words(url.created_at) %> ago by #name</p>
<div class='url-body'>
</div>

app/views/urls/create.html.erb
<h1>Your url for <%= @url.long_url %> is: </h1>
<%= link_to @url.short_url, @url.short_url, target: "_blank" %><br /><br />
<%= link_to "Create another Url", root_path %>

app/views/urls/edit.html.erb
<%=  form_tag url_path, method: :patch do %>
    <div class="url-field">
        <%= label_tag("title") %> <br/>
        <%= text_field_tag("title", @url.title) %>
    </div>

    <div class="url-field">
        <%= label_tag("url") %> <br/>
        <%= text_area_tag("url", @url.url) %>
    </div>

    <%= button_tag("update") %>
<% end %>

app/views/urls/index.html.erb
<nav class="navi-bar">
  <span>hot</span>
  <span>new</span>
  <span>rising</span>
  <span>controversial</span>
  <span>top</span>
  <span>gilded</span>
  <span>wiki</span>
  <span>promoted</span>
</nav>
<div class='url-main'>
    <% @urls.each do |url| %>
  <li>
    <h4><%= link_to url.title, url_path(url) %></h4></br>
      <%= link_to image_tag url.address %>
      <%= link_to @url, Bitly.client.shorten(url.address).short_url %>
      (<%= url.votes.sum(:score) %> points)
      <%= link_to 'up', url_votes_path(url, score: 1), method: :post %>
      <%= link_to 'down', url_votes_path(url, score: -1), method: :post %>
      <p class="url-date">submitted <%= time_ago_in_words(url.created_at) %> by <%= url.user.name %></p>
      <%= link_to("comments", url_path(url)) %>
      <%= link_to("edit", edit_url_path(url)) %>
      <%= link_to("delete", url_path(url), method: :delete) %>
      <span>share</span>
      <span>save</span>
      <span>hide</span>
      <span>report</span>
  </li>
  <% end %>
</div>
<div class='side-main'>
  <div class='url-submit'>
    <%= link_to 'Submit a new url', new_url_path %>
  </div>
  <div class='text-submit'>
    <%= link_to 'Submit a new text post', '#' %>
  </div>
</div>

app/views/urls/new.html.erb
<%= form_for "", url: urls_path, method: :post do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %> <br/>

 <%= f.label :url %>
 <%= f.text_field :address %>
 <%= f.submit 'save' %>
<% end %>

app/views/urls/show.html.erb
<%= render partial: 'url', locals: {url: @url} %>


<h7 class='comments_count'>
  <span>top </span><%= @url.comments.count %> comments<span> show all blah</span>
</h7>

<div class='comments-form'>
    <h6>top 200 comments</h6><%= link_to '#' %>
    <%= form_tag urls_path @url.id do %>
      <div class='comment-field'>
          <%= label_tag('Comment') %>
          <%= text_area_tag('body') %>
      </div>
      <%= button_tag('save') %>
    <% end %>
</div>

<div class='comments-list'>
  <% @url.comments.each do |comment| %>
      <div class='comment-post'>
          <%= User.find(comment.id).name %>
          <%= simple_format(comment.body) %>
      </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%=  form_tag(users_path(@user), method: :put) do %>
    <div class="user-field">
        <%= label_tag("name") %> <br/>
        <%= text_field_tag("name", @user.name) %>
    </div>

    <div class='user-field'>
        <%= label_tag('email') %> <br/>
        <%= text_field_tag('email', @user.email) %>
    </div>

    <div class="user-field">
        <%= label_tag("password") %> <br/>
        <%= text_area_tag("password", @user.password) %>
    </div>

    <%= button_tag("update") %>
<% end %>

app/views/users/new.html.erb
<h5>CREATE A NEW ACCOUNT</h5>

<%= form_tag @user do %>

    <ul class='form-errors'>
        <% if @user.errors.count > 0 %>
            <% @user.errors.full_messages.each do |message| %>
                <li class='form-error'><%= message %></li>
            <% end %>
        <% end %>
    </ul>

    <div class='user-field'>
        <%= label_tag 'Name' %> <br/>
        <%= text_field_tag 'name', @user.name %>
    </div>

    <div class='user-field'>
        <%= label_tag 'Email' %> <br/>
        <%= text_field_tag 'email', @user.email %>
    </div>

    <div class='user-field'>
        <%= label_tag 'Password' %> <br/>
        <%= password_field_tag 'password', @user.password %>
    </div>

    <%= button_tag 'SIGN UP' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>